version: '3.8'

services:
  python-grpc-server:
    build: ./service1
    ports:
      - "50051:50051"
    volumes:
      - ./service1:/app
    tty: true

  python-fastapi-server:
    build: ./service2
    ports:
      - "8089:8089"
    volumes:
      - ./service2:/app
    tty: true