version: '3.8'

services:
  python-grpc-server:
    build: ./grpc-server
    ports:
      - "50051:50051"
    volumes:
      - ./grpc-server:/app
    tty: true

  python-fastapi-server:
    build: ./fastapi-server
    ports:
      - "8089:8089"
    volumes:
      - ./fastapi-server:/app
    tty: true